In [2]:
#importando librerias a utilizar
#libreria para cálculos
import numpy as np
#librería para gráficas
import matplotlib.pyplot as plt

In [3]:
#Definición de vectores y matrices
vec = np.asarray([1, 4, 7])
print("vec = ", vec)

vec =  [1 4 7]


In [11]:
#El vector transpuesto
vecT = vec.transpose()
print(r"vec^T = ", vec.transpose())

vec^T =  [1 4 7]


In [13]:
matrix = np.asarray([[1, 4, 7], [2, 8, 1], [3, 0, 4]])
print("matrix = \n", matrix)

matrix = 
 [[1 4 7]
 [2 8 1]
 [3 0 4]]


In [16]:
vec*matrix

array([[ 1, 16, 49],
       [ 2, 32,  7],
       [ 3,  0, 28]])