## Repaso rápido de Algebra Linear con Python

In [18]:
# En este jupyter notebook se muestran algunas
# de las formas de trabajar con vectores, matrices
# multiplicación matricial y otras herramientas
 
# Autor: Hugo Sánchez-Reyes
# CR IRD-ISTerre
# Julio de 2023

In [3]:
#importando librerias a utilizar
#libreria para cálculos
import numpy as np
#librería par a gráficas
import matplotlib.pyplot as plt

In [5]:
#Definición de vectores y matrices
vec = np.array([1, 4, 7])
print("vec = ", vec)

vec2 = np.array([5, 2, 4])
print('mi vector 2: ', vec2)

vec =  [1 4 7]
mi vector 2:  [5 2 4]


In [6]:
#El vector transpuesto
vecT = vec.transpose()
print(r"vec^T = ", vecT)

vec2T = vec2.transpose()
print('mi vecT = ', vec2T)

#o también
print('o')

vecT = vec.T
print(r"vec^T = ", vec.transpose())

vec^T =  [1 4 7]
mi vecT =  [5 2 4]
o
vec^T =  [1 4 7]


In [8]:
#Producto punto
producto_escalar = vec.dot(vecT)
print('Producto escalar/interno: ', producto_escalar)

result = np.matmul(vec, vecT)
print('Otro método producto escalar/interno: ', producto_escalar)

resultado2 = np.matmul(vec2, vec2T)
print('Mi producto escalar:', resultado2)

Producto escalar/interno:  66
Otro método producto escalar/interno:  66
Mi producto escalar: 45


In [11]:
matrix = np.array([[1, 4, 7], [2, 8, 1], [3, 0, 4]])
print("matrix = \n", matrix)

matrixT = matrix.T
print(" Y la matriz transpuesta = \n", matrixT)

matrix2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
matrix2T = matrix2.T
print('Matriz 2:\n', matrix2)
print('Matriz 2 transpuesta:\n', matrix2T)


matrix = 
 [[1 4 7]
 [2 8 1]
 [3 0 4]]
 Y la matriz transpuesta = 
 [[1 2 3]
 [4 8 0]
 [7 1 4]]
Matriz 2:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Matriz 2 transpuesta:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [14]:
result = np.matmul(vec, matrix)
print('vector mulplicado por matriz: ', result)
result = np.matmul(matrix, vecT)
print('vector transpuesto mulplicado por matriz: ', result)

result2 = np.matmul(vec2, matrix2)
result2t = np.matmul(matrix2, vec2T)
print('vec2 por matriz2:', result2)
print('matriz 2 por vec2T:', result2t)

vector mulplicado por matriz:  [30 36 39]
vector transpuesto mulplicado por matriz:  [66 41 31]
vec2 por matriz2: [5 2 4]
matriz 2 por vec2T: [5 2 4]


In [16]:
# Determinante de una matriz
det_matrix = np.linalg.det(matrix)
print('Determinante de matrix: ', det_matrix)

det_matrix2 = np.linalg.det(matrix2)
print('Determinante de la matriz 2:', det_matrix2)

Determinante de matrix:  -155.99999999999986
Determinante de la matriz 2: 1.0


In [19]:
# Estimaciñon de la inversa de una matriz
inv_matrix = np.linalg.inv(matrix)
print('inversa de la matriz: \n', inv_matrix)

inv_matrix2 = np.linalg.inv(matrix2)
print('inversa de la matriz 2: \n', inv_matrix2)

inversa de la matriz: 
 [[-0.20512821  0.1025641   0.33333333]
 [ 0.03205128  0.10897436 -0.08333333]
 [ 0.15384615 -0.07692308  0.        ]]
inversa de la matriz 2: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# Comprobación del cálculo de la inversa de una matriz
premul = np.matmul(inv_matrix, matrix)
print('Resultado PREmultiplicación: \n', premul)
posmul = np.matmul(matrix, inv_matrix)
print('Resultado POSTmultiplicación: \n', premul)
print('\n')
premul2 = np.matmul(inv_matrix2, matrix2)
print('Resultado PREmultiplicación 2: \n', premul)
posmul2 = np.matmul(matrix2, inv_matrix2)
print('Resultado POSTmultiplicación 2: \n', posmul)

Resultado PREmultiplicación: 
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.38777878e-17 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Resultado POSTmultiplicación: 
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.38777878e-17 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


Resultado PREmultiplicación 2: 
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.38777878e-17 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Resultado POSTmultiplicación 2: 
 [[ 1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
