## Repaso rápido de Algebra Linear con Python

In [18]:
# En este jupyter notebook se muestran algunas
# de las formas de trabajar con vectores, matrices
# multiplicación matricial y otras herramientas


# Autor: Hugo Sánchez-Reyes
# CR IRD-ISTerre
# Julio de 2023

In [19]:
#importando librerias a utilizar
#libreria para cálculos
import numpy as np
#librería para gráficas
import matplotlib.pyplot as plt

In [20]:
#Definición de vectores y matrices
vec = np.asarray([1, 4, 7])
print("vec = ", vec)

vec =  [1 4 7]


In [21]:
#El vector transpuesto
vecT = vec.transpose()
print(r"vec^T = ", vec.transpose())

vec^T =  [1 4 7]


In [22]:
#Producto punto
producto_escalar = vec.dot(vecT)
print('Producto escalar/interno: ', producto_escalar)

result = np.matmul(vec, vecT)
print('Otro método producto escalar/interno: ', producto_escalar)



Producto escalar/interno:  66
Otro método producto escalar/interno:  66


In [23]:
matrix = np.asarray([[1, 4, 7], [2, 8, 1], [3, 0, 4]])
print("matrix = \n", matrix)

matrix = 
 [[1 4 7]
 [2 8 1]
 [3 0 4]]


In [24]:
result = np.matmul(vec, matrix)
print('vector mulplicado por matriz: ', result)

result = np.matmul(matrix, vecT)
print('vector transpuesto mulplicado por matriz: ', result)


vector mulplicado por matriz:  [30 36 39]
vector transpuesto mulplicado por matriz:  [66 41 31]


In [28]:
# Determinante de una matriz
det_matrix = np.linalg.det(matrix)
print('Determinante de matrix: ', det_matrix)

Determinante de matrix:  -155.99999999999986


In [30]:
# Estimaciñon de la inversa de una matriz
inv_matrix = np.linalg.inv(matrix)

In [34]:
# Comprobación del cálculo de la inversa de una matriz
premul = np.matmul(inv_matrix, matrix)
print('Resultado PREmultiplicación: \n', premul)

posmul = np.matmul(matrix, inv_matrix)
print('Resultado POSTmultiplicación: \n', premul)


Resultado PREmultiplicación: 
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.38777878e-17 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Resultado POSTmultiplicación: 
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.38777878e-17 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
